### ISSUE TITLE
Default to n-1 -> n diff

### ISSUE THREAD

**Issue by jamessan** [xfbs/diff.rs#19]
The current default seems to be n -> n-1 diff, so the newest content is being "removed" rather than "added".

Thanks for this tool.  It's super helpful!

**Comment by xfbs** [comment]
Ah, good catch — I've just added this functionality and I didn't realise it. Will fix it timely, am currently working on a few other requested features.

Glad it is of use!

**Comment by xfbs** [comment]
The latest commit should have fixes this, so I'll close this issue. Feel free to open up another one if you think it did not address it.
