### ISSUE TITLE
Unable to read version numbers when dark colorscheme is used

### ISSUE THREAD

**Issue by jamessan** [xfbs/diff.rs#20]
Dark theme:

![navbar-dark](https://github.com/xfbs/diff.rs/assets/112971/fb8588f4-a036-413c-ad3c-ba7b7a8e4e04)

Light theme:

![navbar-light](https://github.com/xfbs/diff.rs/assets/112971/bd03a992-8a53-4315-a00b-cf8789ed3cf2)

**Comment by xfbs** [comment]
Hey @jamessan, I just fixed this in the latest master. Had played around with tailwind and not realized that some of the components still use `yewprint`, which is not really dark-mode aware. Should be fixed now, and I think it looks a little better than before.

In the next step, I'll tackle migrating the code area to use tailwind as well, but that is a bit of a larger refactoring, so it'll likely take a bit longer.
