### ISSUE TITLE
Green "+ X" value barely readable if file is selected

### ISSUE THREAD

**Issue by MrMuetze** [xfbs/diff.rs#22]
Hello everyone!

diff.rs is an essential website for us to review changes whenever we update dependencies and we love it for that, but I've noticed that whenever I select a file the green "+ X" lines indicator becomes basically unreadable. I am using a rather well color-calibrated display whenever I work from home so I think this is not an issue on my side. Maybe it would be possible to switch the colors when a file is selected or choose a different green hue? If I find the time I can try to experiment with this a bit, but for now I've only attached a screenshot of the current situation. I think improving this could also improve the accessibility of the page.

![CleanShot 2024-07-04 at 08 30 40@2x](https://github.com/xfbs/diff.rs/assets/5585613/19576eae-ad56-4a91-932a-163d6338529c)

**Comment by xfbs** [comment]
I'm working on redoing the left navigation component!

**Comment by xfbs** [comment]
I think I'll be able to replace the previous yewprint-based component with a tailwind-based one this weekend. I am horrible at doing web dev stuff, it's a learning curve for me. But hopefully then I can get three things fixed:

- Make dark mode work
- Make it work for mobile (in mobile, I'll do a different layout)
- Add a little bubble behind the digits to make sure the contrast is right even when they are selected

**Comment by xfbs** [comment]
This one should be fixed on latest `master`.
