### ISSUE TITLE
Move CSS rules from `static/style.css` over to `src/tailwind.css` and use tailwind component classes

### ISSUE THREAD

**Issue by xfbs** [xfbs/diff.rs#37]
We currently have two sources of styles:

- `src/tailwind.css`, which contains styles that make use of tailwind component classes
- `static/style.css`, which contains hand-crafted CSS

I think it would make sense to migrate over to just using `src/tailwind.css` (using hand-crafted styles is fine, but just make sure that all style is one place).

**Comment by j-mahapatra** [comment]
Can I work on this?

**Comment by xfbs** [comment]
For sure! Always happy for help, even if small :)
