### ISSUE TITLE
File line numbering

### ISSUE THREAD

**Issue by xfbs** [xfbs/diff.rs#52]
Number of issues here:

- Line numbering starts at zero
- The line number is part of the `pre` element, which is problematic because it means you cannot copy code
- There should be separate line numbers for the left and right versions of the file

Ideally, the solution is to:
- separately count lines, for old + new file. Show appropriate line numbers on inserted/removed lines.
- redesign the underlying HTML layout, such that in the code `pre` element there is only code, and line numbers are in distinct elements.

**Comment by tverghis** [comment]
I think there may be one more issue as well. For the "Show/Fold lines <x> to <y>", `y` might be off-by-one.
![image](https://github.com/user-attachments/assets/3f5f68c5-25bc-4d9c-ab2c-bc6c845aada0)

In the image, lines 12 and 76 are already shown.

**Comment by xfbs** [comment]
Closed by #57
