### ISSUE TITLE
Separate scrolling for files list and contents pane

### ISSUE THREAD

**Issue by Alphare** [xfbs/diff.rs#6]
Hi, first off, thanks for this tool, this will make my job as a maintainer easier. :)

I find myself having to scroll back up quite a bit for larger changes, having a separate scrolling context for the files list could be quite helpful.

**Comment by xfbs** [comment]
Hey, thanks for the feedback! I actually noticed this issue myself too. Especially when you have either a very long file or a very long file list. I can probably fix this pretty easily, despite limited frontend skills.
