### ISSUE TITLE
Don't show double line numbers for fully unchanged files

### ISSUE THREAD

**Issue by xfbs** [xfbs/diff.rs#64]

**Comment by HWienhold** [comment]
Does it make sense to have 2 cols, if both show the absolute count anyway?
![grafik](https://github.com/user-attachments/assets/47867edd-18da-47a6-a251-e18a17d8e1db)

Suggestion would be: make it switchable to show either absolute count as one col or file line numbers as two cols? kind of prepared the second one somehow. (with still the old style though) https://github.com/xfbs/diff.rs/pull/65

**Comment by xfbs** [comment]
You are right, currently both line numbers are always the same.. ideally, we'd track the line numbers for the chunks separately for both files and show the right ones.

I'd also prefer the second one! I think only in the case when you have a file that has no changes at all, then it might make sense to hide the second row (like for the use-case of using diff.rs to just browse a crate's contents).
