### ISSUE TITLE
"Weaken" chunk borders

### ISSUE THREAD

**Issue by HWienhold** [xfbs/diff.rs#72]
Came across this snipped:

![grafik](https://github.com/user-attachments/assets/9609d91c-b58b-4a30-8d79-396a5ca24599)

Maybe it would be sensible to *weaken* the ranges defined by the chunks in the sense, that the difference between chunks should also be at least `CONTEXT_LINES` wide and otherwise combine them?

**Comment by xfbs** [comment]
Sounds sensible to me. Having a single (or two) lines be folded does not make too much sense.
